tasks:
  - name: Run game
    init: g++ -o multiplication_tables src/multiplication_tables.cpp
    command: ./multiplication_tables

github:
  prebuilds:
    addBadge: true
    addComment: false
    addCheck: false
    master: true
    branches: true
    pullRequestsFromForks: true

vscode:
  extensions:
  # - ms-vscode.cpptools
    - twxs.cmake
    - ms-vscode.cmake-tools
    - notskm.clang-tidy
    - DavidAnson.vscode-markdownlint@0.36.1:qV04OEElMWIf9PHKK19GYA==
